version: "3.9"

services:
  backend1:
    image: ealen/echo-server
    networks:
      lbnet:
        ipv4_address: 172.28.0.11

  backend2:
    image: ealen/echo-server
    networks:
      lbnet:
        ipv4_address: 172.28.0.12

  backend3:
    image: ealen/echo-server
    networks:
      lbnet:
        ipv4_address: 172.28.0.13

  bind:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9
    volumes:
      - ./bind/named.conf:/etc/bind/named.conf
      - ./bind/zones:/etc/bind/zones
    networks:
      lbnet:
        ipv4_address: 172.28.0.10

  gateway:
    build: .
    depends_on:
      - bind
      - backend1
      - backend2
      - backend3
    ports:
      - "8080:8080"
    networks:
      lbnet:
        ipv4_address: 172.28.0.20
    dns:
      - 172.28.0.10

networks:
  lbnet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
